#!/bin/bash

if [ -e "src/configs/memory/communication.json" ]; then
    echo
else
    mkdir -p src/configs/memory/communication.json
fi

if [ -e "src/configs/system.brstm" ]; then
    echo
else
    mkdir -p src/configs/system.brstm
fi




if [ "$1" != "" ]; then
    python3 src/core.py "$1"
else
    python3 src/core.py 
fi