#!/bin/sh

if [ -e "$(pwd)/src/configs/memory/communication.json" ]; then
    echo
else
    mkdir -p "$(pwd)/src/configs/memory/communication.json"
fi

if [ -e "$(pwd)/src/configs/system.brstm" ]; then
    echo
else
    mkdir -p "$(pwd)/src/configs/system.brstm"
fi




if [ "$1" != "" ]; then
    python3 "$(pwd)/src/core.py" "$1"
else
    python3 "$(pwd)/src/core.py" 
fi